language: swift

os: osx
osx_image: xcode9.2
cache:
  bundler: true
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --no-use-binaries --platform iOS --cache-builds

script:
  - bundle exec fastlane test
  
# after_success:
#   - bash <(curl -s https://codecov.io/bash)