language: swift

os: osx
osx_image: xcode11.4
cache:
  bundler: true
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --use-xcframeworks --platform iOS --no-use-binaries --cache-builds

script:
  - bundle exec fastlane test

# after_success:
#   - bash <(curl -s https://codecov.io/bash)
